kuali/kc

coeus-impl/src/main/java/org/kuali/coeus/common/budget/framework/personnel/BudgetPersonnelDetails.java, coeus-impl/src/main/java/org/kuali/coeus/common/budget/impl/personnel/BudgetPersonValuesFinder.java, coeus-impl/src/main/java/org/kuali/coeus/common/budget/impl/personnel/BudgetPersonnelRule.java, coeus-impl/src/main/java/org/kuali/coeus/propdev/impl/budget/person/AddProjectPersonnelHelper.java, coeus-impl/src/main/java/org/kuali/coeus/propdev/impl/budget/person/ProposalBudgetProjectPersonnelController.java, coeus-impl/src/main/resources/org/kuali/coeus/propdev/impl/budget/person/ProposalBudgetAssignPersonnelToPeriodsPage.xml
KRACOEUS-8565
Display appointment type and salary effective date in assign personnel to period and edit personnel dialog
Display job code in budget person drop down (add job code to identify same person with different job code)
=> KRACOEUS-8565

coeus-impl/src/main/java/org/kuali/coeus/common/budget/framework/nonpersonnel/BudgetLineItem.java, coeus-impl/src/main/java/org/kuali/coeus/common/budget/impl/print/BudgetBaseStream.java
=> KRACOEUS-7696 : Create Budget Versions Print Action

coeus-impl/src/main/resources/org/kuali/coeus/propdev/impl/core/ProposalDocumentView.xml, coeus-impl/src/main/resources/org/kuali/kra/datadictionary/krad/common/KcApplicationHeader.xml, coeus-webapp/src/main/webapp/css/common/core.css, pom.xml
KRACOEUS-8625 - add view copy cache to proposal, small css fix for app header version
=> KRACOEUS-8625 - add view copy cache to proposal

coeus-impl/src/main/resources/org/kuali/coeus/propdev/impl/budget/modular/ProposalBudgetModularPage.xml
KRACOEUS-8635
Fix for Add Rate dialog issue
=> KRACOEUS-8635

coeus-impl/src/main/java/org/kuali/coeus/common/budget/framework/personnel/BudgetPersonnelDetails.java, coeus-impl/src/main/java/org/kuali/coeus/propdev/impl/budget/nonpersonnel/ProposalBudgetPeriodProjectCostController.java, coeus-impl/src/main/java/org/kuali/coeus/propdev/impl/budget/person/ProposalBudgetProjectPersonnelController.java
KRACOEUS-8632
KRACOEUS-8631
Fix/Verify all budget print forms
Subaward NPE and cost element refresh issue - working after merging code this morning.
=> KRACOEUS-8632

coeus-db/coeus-db-sql/src/main/resources/org/kuali/coeus/coeus-sql/current/6.0.0/dml/KC_DML_01_KRACOEUS-7014_B000.sql, coeus-db/coeus-db-sql/src/main/resources/org/kuali/coeus/coeus-sql/current_mysql/6.0.0/dml/KC_DML_01_KRACOEUS-7014_B000.sql
Easy pickin's - happened to see this in the queue and knew it was a 5-minute fix
=> KRACOEUS-8670: Typo in notifications

coeus-impl/src/main/java/org/kuali/kra/institutionalproposal/contacts/InstitutionalProposalProjectPersonAddRuleImpl.java, coeus-impl/src/main/resources/ApplicationResources.properties
Just add to conditions that define a key role in IP, where a person cannot hold more than 1 of these roles.
I also corrected a few typo's that I found in the applicationresources.properties file, since I was in there anyway.
=> KRACOEUS-8673: Key personnel can be duplicated in IP

coeus-impl/src/main/java/org/kuali/coeus/common/budget/impl/calculator/BudgetCalculationServiceImpl.java
KRACOEUS-8605
Fix budget settings changes not applied to personnel
Test Modular sync
=> KRACOEUS-8605

coeus-impl/src/main/java/org/kuali/coeus/propdev/impl/budget/ProposalBudgetService.java, coeus-impl/src/main/java/org/kuali/coeus/propdev/impl/budget/ProposalBudgetServiceImpl.java, coeus-impl/src/main/java/org/kuali/coeus/propdev/impl/budget/core/ProposalBudgetViewHelperServiceImpl.java, coeus-impl/src/main/resources/org/kuali/coeus/propdev/impl/budget/core/ProposalBudgetView.xml
KRACOEUS-8653
Budget final version - updated to marked for submission.
Indicate whether budget version is marked for submission
=> KRACOEUS-8653

coeus-impl/src/main/resources/org/kuali/coeus/propdev/impl/person/ProposalPersonnelPage.xml, coeus-webapp/src/main/webapp/scripts/propdev/person.js
Enable Server Side Paging for Key Personnel page.  Use Ajax for tabs.
=> KULRICE-14086.  

coeus-impl/src/main/resources/org/kuali/coeus/propdev/impl/core/ProposalSubmitPage.xml
KRACOEUS-8483
Fix STE on disapprove action
Remove confirm navigation
=> KRACOEUS-8483

coeus-impl/src/main/java/org/kuali/coeus/propdev/impl/auth/ProposalDevelopmentDocumentViewAuthorizer.java, coeus-impl/src/main/java/org/kuali/coeus/propdev/impl/core/ProposalDevelopmentControllerBase.java, coeus-impl/src/main/java/org/kuali/coeus/propdev/impl/core/ProposalDocumentView.java, coeus-impl/src/main/java/org/kuali/coeus/propdev/impl/lock/ProposalBudgetLockServiceImpl.java, coeus-impl/src/main/java/org/kuali/coeus/sys/impl/lock/KcPessimisticLockService.java, coeus-impl/src/main/java/org/kuali/coeus/sys/impl/lock/KcPessimisticLockServiceImpl.java, coeus-impl/src/main/resources/org/kuali/coeus/propdev/impl/PropDevImportModuleSpringBeans.xml
=> KRACOEUS_8638: KRACOEUS-8638:narrative lock makes access readOnly, access page creat..

coeus-db/coeus-db-xml/src/main/resources/org/kuali/coeus/coeus-xml/2/ProposalDevelopmentDocument.xml, coeus-impl/src/main/java/org/kuali/coeus/sys/framework/workflow/KcPostProcessor.java
not sure if i wired this in spring correctly, the autowiring wasn't working producing npe's and when i tried to set the WorkflowDoucment and GlobalVariable service in the Override spring beans that application wouldn't start,  using service locators in the the getters was the only method I could get to work.
=> KRACOEUS-7658:fixed routing to set the correct update user

coeus-impl/src/main/resources/org/kuali/coeus/propdev/impl/s2s/ProposalOpportunitySearchPage.xml, coeus-webapp/src/main/webapp/scripts/propdev/s2s.js
=> KRACOEUS-8436 PD UXI: S2S Form Print - Select All selects all Available forms, not all Included forms

coeus-impl/src/main/java/org/kuali/coeus/propdev/impl/budget/core/ProposalBudgetSharedControllerServiceImpl.java
KRACOEUS-8649
Set form name as report name when only one form is selected or set a generic name for multiple print forms.
=> KRACOEUS-8649

coeus-impl/src/main/java/org/kuali/coeus/org/kuali/rice/krad/uif/container/KcCollectionGroupBase.java, coeus-impl/src/main/java/org/kuali/coeus/propdev/impl/questionnaire/QuestionnaireTabGroup.java, coeus-impl/src/main/resources/org/kuali/coeus/propdev/impl/person/ProposalPersonnelPage.xml, coeus-impl/src/main/resources/org/kuali/kra/datadictionary/krad/common/KcComponents.xml
Work-around to get Ajax working with disclosure triangles.  Initial page load is much faster, although disclosure triangles initially render as closed.  (Not sure if this is a user experience issue.)
=> KULRICE-14086 -  Ajax disclosure triangles.

coeus-impl/src/main/resources/org/kuali/coeus/propdev/impl/budget/modular/ProposalBudgetModularPage.xml
KRACOEUS-8706
Add validation to budget modular
=> KRACOEUS-8706

coeus-impl/src/main/java/org/kuali/coeus/propdev/impl/sponsor/ProposalDevelopmentSponsorProgramInformationAuditRule.java
KRACOEUS-8721
Ignore time in current date for comparison
=> KRACOEUS-8721

coeus-impl/src/main/resources/org/kuali/kra/CoreSpringBeans.xml
KRACOEUS-8006
KRACOEUS-8712
Addressing these jiras I am not able to reproduce the issue.
Testing above, initially I was not able to create an award as the Payment, Reports and Terms tab was
not loading due to attributeEntry null error.
Adding AwardCgb to core spring bean to fix this issue.
=> KRACOEUS-8006

coeus-impl/src/main/java/org/kuali/coeus/propdev/impl/budget/ProposalBudgetNumberOfMonthsServiceImpl.java, coeus-impl/src/test/java/org/kuali/coeus/propdev/impl/budget/ProposalBudgetNumberOfMonthsServiceTest.java
KRACOEUS-8727
Fix months calculation in budget periods
=> KRACOEUS-8727

coeus-impl/src/test/java/org/kuali/kra/award/printing/service/impl/AwardPrintingServiceImplTest.java
The one time I don't make sure CheckPR runs... *shakes head in shame*
=> KRACOEUS-8129 : Fix unit test

coeus-impl/src/main/java/org/kuali/coeus/propdev/impl/basic/ProposalDevelopmentHomeController.java, coeus-impl/src/main/java/org/kuali/coeus/propdev/impl/budget/core/ProposalBudgetCommonController.java, coeus-impl/src/main/java/org/kuali/coeus/propdev/impl/budget/core/ProposalBudgetController.java, coeus-impl/src/main/java/org/kuali/coeus/propdev/impl/budget/core/ProposalBudgetForm.java, coeus-impl/src/main/java/org/kuali/coeus/propdev/impl/budget/core/ProposalBudgetSharedControllerService.java, coeus-impl/src/main/java/org/kuali/coeus/propdev/impl/budget/core/ProposalBudgetSharedControllerServiceImpl.java, coeus-impl/src/main/resources/org/kuali/coeus/propdev/impl/budget/core/ProposalBudgetShared.xml, coeus-impl/src/main/resources/org/kuali/coeus/propdev/impl/budget/core/ProposalBudgetView.xml
KRACOEUS-8728
Fix to open budget in view mode when proposal is in view mode
Also in account return back to proposal.
=> KRACOEUS-8728

coeus-impl/src/main/java/org/kuali/coeus/propdev/impl/budget/ProposalBudgetNumberOfMonthsServiceImpl.java, coeus-impl/src/test/java/org/kuali/coeus/propdev/impl/budget/ProposalBudgetNumberOfMonthsServiceTest.java
KRACOEUS-8735
Calculate months last day inclusive.
=> KRACOEUS-8735

coeus-db/coeus-db-sql/pom.xml, coeus-db/coeus-db-xml/pom.xml, coeus-db/pom.xml, coeus-help/pom.xml, coeus-impl/pom.xml, coeus-it/pom.xml, coeus-tool/pom.xml, coeus-webapp/pom.xml, pom.xml
=> Revert "KRACOEUS-8750: sprint 14"

coeus-db/coeus-db-sql/src/main/resources/org/kuali/coeus/coeus-sql/current/6.0.0/dml/KC_DML_01_KRACOEUS-8128_B000.sql, coeus-db/coeus-db-sql/src/main/resources/org/kuali/coeus/coeus-sql/current_mysql/6.0.0/dml/KC_DML_01_KRACOEUS-8128_B000.sql
=> KRACOEUS-8128 fix fop error: ProtocolActionCorrespondenceGenerationServiceTest

coeus-impl/src/main/java/org/kuali/kra/iacuc/IacucProtocolDocument.java, coeus-impl/src/main/java/org/kuali/kra/irb/ProtocolDocument.java, coeus-impl/src/main/java/org/kuali/kra/protocol/ProtocolDocumentBase.java
KRACOEUS-8523
Blanket approve merged protocol document - IRB and IACUC.
Issue in this JIRA is that the new document not approved.
Status was ENROUTE not FINAL
Fixed in both IRB and IACUC
=> KRACOEUS-8523

coeus-it/src/test/java/org/kuali/coeus/propdev/impl/copy/ProposalCopyServiceTest.java
still getting errors in ci, ignoring test for now, as i can't reproduce locally
=> KRACOEUS-8664:ignoring proposalcopyservicetest

pom.xml
I tested that everything builds ok.
=> KRACOEUS-8344: setting lib versions for release

coeus-db/coeus-db-sql/pom.xml, coeus-db/coeus-db-xml/pom.xml, coeus-db/pom.xml, coeus-help/pom.xml, coeus-impl/pom.xml, coeus-it/pom.xml, coeus-tool/pom.xml, coeus-webapp/pom.xml, pom.xml
after our release build is done, please merge
=> KRACOEUS-8775: next iteration

coeus-impl/src/main/resources/org/kuali/kra/datadictionary/krad/common/KcApplicationHeader.xml, coeus-webapp/src/main/webapp/css/common/core.css
per @blackcathacker request moved version and sql version to footer
=> KRACOEUS-8760:moved version and sql info to footer

coeus-impl/src/main/java/org/kuali/coeus/common/budget/framework/calculator/BudgetCalculationService.java, coeus-impl/src/main/java/org/kuali/coeus/common/budget/framework/nonpersonnel/BudgetFormulatedCostDetail.java, coeus-impl/src/main/java/org/kuali/coeus/common/budget/impl/calculator/BudgetCalculationServiceImpl.java, coeus-impl/src/main/java/org/kuali/coeus/common/budget/impl/personnel/BudgetPersonnelBudgetServiceImpl.java, coeus-impl/src/main/java/org/kuali/coeus/propdev/impl/budget/nonpersonnel/ProposalBudgetPeriodProjectCostController.java, coeus-impl/src/main/resources/org/kuali/coeus/propdev/impl/budget/nonpersonnel/ProposalBudgetNonPersonnelCostsPage.xml
KRACOEUS-7863
Implement Budget Non-Personnel Costs - Formulated Costs
=> KRACOEUS-7863

coeus-impl/src/main/resources/org/kuali/kra/datadictionary/NegotiationUnassociatedDetail.xml
Changing "Sponsor Award" label to "Sponsor Award ID" in Negotiation.
=> [KRAFDBCK-9468] Changing "Sponsor Award" label to "Sponsor Award ID"
